[package]
name = "luisa-python-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29.2", optional = true }


[build-dependencies]

[features]
default = ["glam"]
glam = ["dep:glam"]
