[package]
name = "luisa-python-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
jit = ["pyo3"]
